version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:5.7'
    container_name: db_docker_symfonybase
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'
  
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_docker_symfonybase
    restart: always
    depends_on:
        - database
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
  
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
